// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v5.28.1
// source: heyo.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "rpc";

export enum AckCode {
  /** OK - Message successfully received */
  OK = 0,
  /** NO_LISTENER - No matching subscriber for the event */
  NO_LISTENER = 1,
  /** QUEUE_FULL - Queue is full, unable to receive message */
  QUEUE_FULL = 2,
  /** INTERNAL_ERROR - General server-side error */
  INTERNAL_ERROR = 3,
  UNKNOWN_EVENT = 4,
  UNRECOGNIZED = -1,
}

export function ackCodeFromJSON(object: any): AckCode {
  switch (object) {
    case 0:
    case "OK":
      return AckCode.OK;
    case 1:
    case "NO_LISTENER":
      return AckCode.NO_LISTENER;
    case 2:
    case "QUEUE_FULL":
      return AckCode.QUEUE_FULL;
    case 3:
    case "INTERNAL_ERROR":
      return AckCode.INTERNAL_ERROR;
    case 4:
    case "UNKNOWN_EVENT":
      return AckCode.UNKNOWN_EVENT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AckCode.UNRECOGNIZED;
  }
}

export function ackCodeToJSON(object: AckCode): string {
  switch (object) {
    case AckCode.OK:
      return "OK";
    case AckCode.NO_LISTENER:
      return "NO_LISTENER";
    case AckCode.QUEUE_FULL:
      return "QUEUE_FULL";
    case AckCode.INTERNAL_ERROR:
      return "INTERNAL_ERROR";
    case AckCode.UNKNOWN_EVENT:
      return "UNKNOWN_EVENT";
    case AckCode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Empty {
}

export interface Handshake {
  clientUuid: string;
}

export interface Message {
  event: string;
  data: string;
  messageId: string;
  clientId: string;
  clientName: string;
}

export interface Subscriber {
  event: string;
  clientId: string;
  name: string;
}

export interface Ack {
  data: string;
  code: AckCode;
}

function createBaseEmpty(): Empty {
  return {};
}

export const Empty: MessageFns<Empty> = {
  encode(_: Empty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Empty {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Empty {
    return {};
  },

  toJSON(_: Empty): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Empty>, I>>(base?: I): Empty {
    return Empty.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Empty>, I>>(_: I): Empty {
    const message = createBaseEmpty();
    return message;
  },
};

function createBaseHandshake(): Handshake {
  return { clientUuid: "" };
}

export const Handshake: MessageFns<Handshake> = {
  encode(message: Handshake, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientUuid !== "") {
      writer.uint32(10).string(message.clientUuid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Handshake {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHandshake();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clientUuid = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Handshake {
    return { clientUuid: isSet(object.clientUuid) ? globalThis.String(object.clientUuid) : "" };
  },

  toJSON(message: Handshake): unknown {
    const obj: any = {};
    if (message.clientUuid !== "") {
      obj.clientUuid = message.clientUuid;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Handshake>, I>>(base?: I): Handshake {
    return Handshake.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Handshake>, I>>(object: I): Handshake {
    const message = createBaseHandshake();
    message.clientUuid = object.clientUuid ?? "";
    return message;
  },
};

function createBaseMessage(): Message {
  return { event: "", data: "", messageId: "", clientId: "", clientName: "" };
}

export const Message: MessageFns<Message> = {
  encode(message: Message, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.event !== "") {
      writer.uint32(10).string(message.event);
    }
    if (message.data !== "") {
      writer.uint32(18).string(message.data);
    }
    if (message.messageId !== "") {
      writer.uint32(26).string(message.messageId);
    }
    if (message.clientId !== "") {
      writer.uint32(34).string(message.clientId);
    }
    if (message.clientName !== "") {
      writer.uint32(42).string(message.clientName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Message {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.event = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.messageId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.clientName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Message {
    return {
      event: isSet(object.event) ? globalThis.String(object.event) : "",
      data: isSet(object.data) ? globalThis.String(object.data) : "",
      messageId: isSet(object.messageId) ? globalThis.String(object.messageId) : "",
      clientId: isSet(object.clientId) ? globalThis.String(object.clientId) : "",
      clientName: isSet(object.clientName) ? globalThis.String(object.clientName) : "",
    };
  },

  toJSON(message: Message): unknown {
    const obj: any = {};
    if (message.event !== "") {
      obj.event = message.event;
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    if (message.messageId !== "") {
      obj.messageId = message.messageId;
    }
    if (message.clientId !== "") {
      obj.clientId = message.clientId;
    }
    if (message.clientName !== "") {
      obj.clientName = message.clientName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Message>, I>>(base?: I): Message {
    return Message.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Message>, I>>(object: I): Message {
    const message = createBaseMessage();
    message.event = object.event ?? "";
    message.data = object.data ?? "";
    message.messageId = object.messageId ?? "";
    message.clientId = object.clientId ?? "";
    message.clientName = object.clientName ?? "";
    return message;
  },
};

function createBaseSubscriber(): Subscriber {
  return { event: "", clientId: "", name: "" };
}

export const Subscriber: MessageFns<Subscriber> = {
  encode(message: Subscriber, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.event !== "") {
      writer.uint32(10).string(message.event);
    }
    if (message.clientId !== "") {
      writer.uint32(18).string(message.clientId);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Subscriber {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscriber();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.event = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Subscriber {
    return {
      event: isSet(object.event) ? globalThis.String(object.event) : "",
      clientId: isSet(object.clientId) ? globalThis.String(object.clientId) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: Subscriber): unknown {
    const obj: any = {};
    if (message.event !== "") {
      obj.event = message.event;
    }
    if (message.clientId !== "") {
      obj.clientId = message.clientId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Subscriber>, I>>(base?: I): Subscriber {
    return Subscriber.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Subscriber>, I>>(object: I): Subscriber {
    const message = createBaseSubscriber();
    message.event = object.event ?? "";
    message.clientId = object.clientId ?? "";
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseAck(): Ack {
  return { data: "", code: 0 };
}

export const Ack: MessageFns<Ack> = {
  encode(message: Ack, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== "") {
      writer.uint32(10).string(message.data);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Ack {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAck();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Ack {
    return {
      data: isSet(object.data) ? globalThis.String(object.data) : "",
      code: isSet(object.code) ? ackCodeFromJSON(object.code) : 0,
    };
  },

  toJSON(message: Ack): unknown {
    const obj: any = {};
    if (message.data !== "") {
      obj.data = message.data;
    }
    if (message.code !== 0) {
      obj.code = ackCodeToJSON(message.code);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Ack>, I>>(base?: I): Ack {
    return Ack.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Ack>, I>>(object: I): Ack {
    const message = createBaseAck();
    message.data = object.data ?? "";
    message.code = object.code ?? 0;
    return message;
  },
};

export type BrokerService = typeof BrokerService;
export const BrokerService = {
  /**
   * Server side: handle message reception and dispatch
   *
   * Client side: put a message to the queue
   */
  enqueue: {
    path: "/rpc.Broker/Enqueue",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: Message): Buffer => Buffer.from(Message.encode(value).finish()),
    requestDeserialize: (value: Buffer): Message => Message.decode(value),
    responseSerialize: (value: Ack): Buffer => Buffer.from(Ack.encode(value).finish()),
    responseDeserialize: (value: Buffer): Ack => Ack.decode(value),
  },
  /**
   * Server side: handle subscribing clients
   *
   * Client side: subscribe to an event
   */
  subscription: {
    path: "/rpc.Broker/Subscription",
    requestStream: false,
    responseStream: true,
    requestSerialize: (value: Subscriber): Buffer => Buffer.from(Subscriber.encode(value).finish()),
    requestDeserialize: (value: Buffer): Subscriber => Subscriber.decode(value),
    responseSerialize: (value: Message): Buffer => Buffer.from(Message.encode(value).finish()),
    responseDeserialize: (value: Buffer): Message => Message.decode(value),
  },
} as const;

export interface BrokerServer extends UntypedServiceImplementation {
  /**
   * Server side: handle message reception and dispatch
   *
   * Client side: put a message to the queue
   */
  enqueue: handleUnaryCall<Message, Ack>;
  /**
   * Server side: handle subscribing clients
   *
   * Client side: subscribe to an event
   */
  subscription: handleServerStreamingCall<Subscriber, Message>;
}

export interface BrokerClient extends Client {
  /**
   * Server side: handle message reception and dispatch
   *
   * Client side: put a message to the queue
   */
  enqueue(request: Message, callback: (error: ServiceError | null, response: Ack) => void): ClientUnaryCall;
  enqueue(
    request: Message,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Ack) => void,
  ): ClientUnaryCall;
  enqueue(
    request: Message,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Ack) => void,
  ): ClientUnaryCall;
  /**
   * Server side: handle subscribing clients
   *
   * Client side: subscribe to an event
   */
  subscription(request: Subscriber, options?: Partial<CallOptions>): ClientReadableStream<Message>;
  subscription(request: Subscriber, metadata?: Metadata, options?: Partial<CallOptions>): ClientReadableStream<Message>;
}

export const BrokerClient = makeGenericClientConstructor(BrokerService, "rpc.Broker") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): BrokerClient;
  service: typeof BrokerService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
