// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.1
// source: heyo.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AckCode int32

const (
	AckCode_OK             AckCode = 0 // Message successfully received
	AckCode_NO_LISTENER    AckCode = 1 // No matching subscriber for the event
	AckCode_QUEUE_FULL     AckCode = 2 // Queue is full, unable to receive message
	AckCode_INTERNAL_ERROR AckCode = 3 // General server-side error
	AckCode_UNKNOWN_EVENT  AckCode = 4
)

// Enum value maps for AckCode.
var (
	AckCode_name = map[int32]string{
		0: "OK",
		1: "NO_LISTENER",
		2: "QUEUE_FULL",
		3: "INTERNAL_ERROR",
		4: "UNKNOWN_EVENT",
	}
	AckCode_value = map[string]int32{
		"OK":             0,
		"NO_LISTENER":    1,
		"QUEUE_FULL":     2,
		"INTERNAL_ERROR": 3,
		"UNKNOWN_EVENT":  4,
	}
)

func (x AckCode) Enum() *AckCode {
	p := new(AckCode)
	*p = x
	return p
}

func (x AckCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckCode) Descriptor() protoreflect.EnumDescriptor {
	return file_heyo_proto_enumTypes[0].Descriptor()
}

func (AckCode) Type() protoreflect.EnumType {
	return &file_heyo_proto_enumTypes[0]
}

func (x AckCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckCode.Descriptor instead.
func (AckCode) EnumDescriptor() ([]byte, []int) {
	return file_heyo_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_heyo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_heyo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_heyo_proto_rawDescGZIP(), []int{0}
}

type Handshake struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientUuid string `protobuf:"bytes,1,opt,name=client_uuid,json=clientUuid,proto3" json:"client_uuid,omitempty"`
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_heyo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_heyo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_heyo_proto_rawDescGZIP(), []int{1}
}

func (x *Handshake) GetClientUuid() string {
	if x != nil {
		return x.ClientUuid
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event       string `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Data        string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	MessageUuid string `protobuf:"bytes,3,opt,name=message_uuid,json=messageUuid,proto3" json:"message_uuid,omitempty"`
	ClientUuid  string `protobuf:"bytes,4,opt,name=client_uuid,json=clientUuid,proto3" json:"client_uuid,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_heyo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_heyo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_heyo_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *Message) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Message) GetMessageUuid() string {
	if x != nil {
		return x.MessageUuid
	}
	return ""
}

func (x *Message) GetClientUuid() string {
	if x != nil {
		return x.ClientUuid
	}
	return ""
}

type Subscriber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event      string `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	ClientUuid string `protobuf:"bytes,2,opt,name=client_uuid,json=clientUuid,proto3" json:"client_uuid,omitempty"`
}

func (x *Subscriber) Reset() {
	*x = Subscriber{}
	mi := &file_heyo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscriber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscriber) ProtoMessage() {}

func (x *Subscriber) ProtoReflect() protoreflect.Message {
	mi := &file_heyo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscriber.ProtoReflect.Descriptor instead.
func (*Subscriber) Descriptor() ([]byte, []int) {
	return file_heyo_proto_rawDescGZIP(), []int{3}
}

func (x *Subscriber) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *Subscriber) GetClientUuid() string {
	if x != nil {
		return x.ClientUuid
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Code AckCode `protobuf:"varint,2,opt,name=code,proto3,enum=rpc.AckCode" json:"code,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_heyo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_heyo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_heyo_proto_rawDescGZIP(), []int{4}
}

func (x *Ack) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Ack) GetCode() AckCode {
	if x != nil {
		return x.Code
	}
	return AckCode_OK
}

var File_heyo_proto protoreflect.FileDescriptor

var file_heyo_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x68, 0x65, 0x79, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70,
	0x63, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x2c, 0x0a, 0x09, 0x48, 0x61,
	0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x55, 0x75, 0x69, 0x64, 0x22, 0x77, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a,
	0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x55, 0x75, 0x69, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x55, 0x75, 0x69,
	0x64, 0x22, 0x43, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x55, 0x75, 0x69, 0x64, 0x22, 0x3b, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x20, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x63, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x2a, 0x59, 0x0a, 0x07, 0x41, 0x63, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x06,
	0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x4f, 0x5f, 0x4c, 0x49, 0x53,
	0x54, 0x45, 0x4e, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x51, 0x55, 0x45, 0x55, 0x45,
	0x5f, 0x46, 0x55, 0x4c, 0x4c, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x54, 0x45, 0x52,
	0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x10, 0x04, 0x32, 0x60,
	0x0a, 0x06, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x07, 0x45, 0x6e, 0x71, 0x75,
	0x65, 0x75, 0x65, 0x12, 0x0c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x08, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x63, 0x6b, 0x22, 0x00, 0x12, 0x31, 0x0a,
	0x0c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0f, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x1a, 0x0c,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x30, 0x01,
	0x42, 0x09, 0x5a, 0x07, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_heyo_proto_rawDescOnce sync.Once
	file_heyo_proto_rawDescData = file_heyo_proto_rawDesc
)

func file_heyo_proto_rawDescGZIP() []byte {
	file_heyo_proto_rawDescOnce.Do(func() {
		file_heyo_proto_rawDescData = protoimpl.X.CompressGZIP(file_heyo_proto_rawDescData)
	})
	return file_heyo_proto_rawDescData
}

var file_heyo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_heyo_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_heyo_proto_goTypes = []any{
	(AckCode)(0),       // 0: rpc.AckCode
	(*Empty)(nil),      // 1: rpc.Empty
	(*Handshake)(nil),  // 2: rpc.Handshake
	(*Message)(nil),    // 3: rpc.Message
	(*Subscriber)(nil), // 4: rpc.Subscriber
	(*Ack)(nil),        // 5: rpc.Ack
}
var file_heyo_proto_depIdxs = []int32{
	0, // 0: rpc.Ack.code:type_name -> rpc.AckCode
	3, // 1: rpc.Broker.Enqueue:input_type -> rpc.Message
	4, // 2: rpc.Broker.Subscription:input_type -> rpc.Subscriber
	5, // 3: rpc.Broker.Enqueue:output_type -> rpc.Ack
	3, // 4: rpc.Broker.Subscription:output_type -> rpc.Message
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_heyo_proto_init() }
func file_heyo_proto_init() {
	if File_heyo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_heyo_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_heyo_proto_goTypes,
		DependencyIndexes: file_heyo_proto_depIdxs,
		EnumInfos:         file_heyo_proto_enumTypes,
		MessageInfos:      file_heyo_proto_msgTypes,
	}.Build()
	File_heyo_proto = out.File
	file_heyo_proto_rawDesc = nil
	file_heyo_proto_goTypes = nil
	file_heyo_proto_depIdxs = nil
}
